# docker-compose.yml — PROD uniquement
services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    restart: always
    command:
      - "--api.dashboard=false"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:8443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contact.gohope@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.go-hope.fr`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$ruca84Hq$$dQIZkQR71ZMiqJMct6SyZ0"
      - "traefik.http.routers.traefik.middlewares=auth"
    mem_limit: 256M

  frontend-prod:
    build:
      context: ./Go-hope-app
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    restart: unless-stopped
    expose:
      - "80"
    env_file:
      - ./API/.env
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-prod.rule=Host(`app.go-hope.fr`)"
      - "traefik.http.routers.frontend-prod.entrypoints=websecure"
      - "traefik.http.routers.frontend-prod.tls.certresolver=myresolver"
      - "traefik.http.services.frontend-prod.loadbalancer.server.port=80"
    networks:
      - web
    mem_limit: 256M

  backend-prod:
    build:
      context: ./API
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - /var/www/Go-hope/uploads:/app/uploads
    env_file:
      - ./API/.env
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-prod.rule=Host(`api.go-hope.fr`)"
      - "traefik.http.routers.backend-prod.entrypoints=websecure"
      - "traefik.http.routers.backend-prod.tls.certresolver=myresolver"
      - "traefik.http.services.backend-prod.loadbalancer.server.port=5000"
    networks:
      - web
    mem_limit: 512M

networks:
  web:
    external: true

volumes:
  letsencrypt:
