name: Deploy to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Mylizy
            git pull origin dev
            cd /var/www/Mylizy

            docker-compose down
            docker-compose pull
            docker-compose build --no-cache
            docker-compose up -d --remove-orphans
            echo "Déploiement avec Docker terminé avec succès."
