name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/go-hope

            # Désactiver BuildKit pour éviter le bug ContainerConfig
            export DOCKER_BUILDKIT=0

            echo "Pulling latest code..."
            git pull origin main

            echo "Building and deploying containers..."
            # Arrêter seulement frontend et backend (garder traefik)
            docker-compose stop frontend backend
            docker-compose rm -f frontend backend

            # Build sans cache pour corriger l'erreur de syntaxe
            docker-compose build frontend backend

            # Redémarrer
            docker-compose up -d frontend backend

            echo "Déploiement terminé avec succès."
