name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/go-hope

            echo "Pulling latest code..."
            git pull origin main

            echo "Building and deploying containers..."
            docker-compose down go-hope-frontend go-hope-backend
            docker-compose build --no-cache go-hope-frontend go-hope-backend
            docker-compose up -d go-hope-frontend go-hope-backend

            echo "Deployment completed successfully!"
