name: Deploy to VPS (prod only)

on:
  push:
    branches:
      - main # déploiement auto uniquement sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Déploiement SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          command_timeout: 30m
          envs: GITHUB_SHA
          script: |
            set -e

            echo "=> Connexion au serveur — déploiement commit $GITHUB_SHA"
            cd /var/www/go-hope

            # Pull les sources
            git fetch origin main
            git reset --hard origin/main

            # Option 1: Arrêter et supprimer les conteneurs par leur nom
            docker stop go-hope-frontend-1 go-hope-backend-1 || true
            docker rm go-hope-frontend-1 go-hope-backend-1 || true

            # Option 2: Ou utiliser docker-compose down qui arrête et supprime tout
            # docker compose down

            # Build et démarrer les services (en utilisant les noms de services)
            export DOCKER_BUILDKIT=1
            docker compose build frontend backend
            docker compose up -d frontend backend

            echo "✅ Déploiement terminé"
