name: Deploy to VPS (prod only)

on:
  push:
    branches:
      - main # déploiement auto uniquement sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Déploiement SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}

          command_timeout: 30m # Remplace script_timeout qui n'existe pas
          envs: GITHUB_SHA
          script: |
            set -e

            echo "=> Connexion au serveur — déploiement commit $GITHUB_SHA"
            cd /var/www/go-hope

            # Pull les sources
            git fetch origin main
            git reset --hard origin/main

            # Afficher les services disponibles pour debug
            echo "Services disponibles:"
            docker compose config --services


            # Build + up des services prod uniquement
            # Utilisez les noms exacts des services de votre docker-compose.yml
            export DOCKER_BUILDKIT=1
            docker compose stop frontend-prod backend-prod || true
            docker compose rm -f frontend-prod backend-prod || true
            docker compose build frontend-prod backend-prod
            docker compose up -d --remove-orphans frontend-prod backend-prod

            echo "✅ Déploiement terminé"
