name: Deploy to VPS (prod only)

on:
  push:
    branches:
      - main # déploiement auto uniquement sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Déploiement SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          command_timeout: 30m
          envs: GITHUB_SHA
          script: |
            set -e

            echo "=> Connexion au serveur — déploiement commit $GITHUB_SHA"
            cd /var/www/go-hope

            # Pull les sources
            git fetch origin main
            git reset --hard origin/main

            # Afficher les services disponibles pour debug
            echo "Services disponibles:"
            docker compose config --services

            # Build + up des services (utilisez les noms exacts des services dans docker-compose.yml)
            export DOCKER_BUILDKIT=1
            docker compose stop frontend backend || true
            docker compose rm -f frontend backend || true
            docker compose build frontend backend
            docker compose up -d --remove-orphans frontend backend

            echo "✅ Déploiement terminé"
