name: Deploy to Production

on:
  push:
    branches:
      - main # Seulement déploiement depuis main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          command_timeout: 30m
          script: |
            cd /var/www/go-hope

            # Pull les sources du projet
            git fetch origin main
            git reset --hard origin/main

            # Activer BuildKit pour des builds plus rapides
            export DOCKER_BUILDKIT=1

            # Nettoyage et redémarrage des conteneurs
            docker compose stop frontend backend
            docker compose rm -f frontend backend
            docker compose build --no-cache frontend backend
            docker compose up -d --remove-orphans frontend backend

            echo "Déploiement terminé avec succès."
