name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/go-hope

            # Désactiver BuildKit pour éviter le bug ContainerConfig
            export DOCKER_BUILDKIT=0

            echo "Déploiement production (frontend et backend)"
            git pull origin main

            # Nettoyage des conteneurs existants
            docker-compose stop frontend backend
            docker-compose rm -f frontend backend

            # Libération d'espace disque
            docker system prune -f

            # Construction et démarrage des services
            docker-compose build --no-cache frontend backend
            docker-compose up -d --remove-orphans frontend backend

            echo "Déploiement avec Docker terminé avec succès."
