name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/go-hope

            # Désactiver BuildKit pour éviter le bug ContainerConfig
            export DOCKER_BUILDKIT=0

            # Récupère la branche qui a déclenché le workflow
            BRANCH="${{ github.ref }}"
            echo "Branche déclenchante : $BRANCH"

            if [ "$BRANCH" = "refs/heads/main" ]; then
              echo "Déploiement production (frontend et backend)"
              git pull origin main
              docker-compose stop frontend backend
              docker-compose rm -f frontend backend
              docker-compose pull frontend backend
              docker-compose build --no-cache frontend backend
              docker-compose up -d --remove-orphans frontend backend
            fi

            echo "Déploiement avec Docker terminé avec succès."
